services:
  app:
    image: 'docker-app:latest'
    container_name: docker-app
    build:
      context: .
    ports:
      - '8080:8080'
    environment:
      MONGODB_HOST: "mongodb"
      MONGODB_DBNAME: "dockers_demo"
      MONGODB_USERNAME: "devroot"
      MONGODB_PASSWORD: "qwerty123"
      MONGODB_PORT: "27017"
      SPRING_PROFILES_ACTIVE: "dev"
    networks:
      - my-docker-project
    links:
      - mongodb
    depends_on:
      mongodb:
        condition: service_started
  mongodb:
    image: mongo:latest
    container_name: mongodb
    hostname: mongodb
    restart: always
    environment:
      - 'MONGO_INITDB_DATABASE=dockers_demo'
      - 'MONGO_INITDB_ROOT_USERNAME=devroot'
      - 'MONGO_INITDB_ROOT_PASSWORD=qwerty123'
    ports:
      - '27018:27017'
    volumes:
      - ./data/data:/data/db
    networks:
      - my-docker-project
volumes:
  data: {}
networks:
  my-docker-project:
    driver: bridge
